/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 187dc7ef5a6fe5b2137a00c653131c67)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	ADMIN_PASSWORD: string;
	ADMIN_SESSION_SECRET: string;
	OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_D1_TOKEN" | "ADMIN_PASSWORD" | "ADMIN_SESSION_SECRET" | "OPENAI_API_KEY">> {}
}
