/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 165991557f528cd77092c8eb90acd0f0)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
